// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMMULprgMsPCsL5LBdcAuvsCCukmUdZOM',
    appId: '1:1078406388474:android:f012c2558b35273161c743',
    messagingSenderId: '1078406388474',
    projectId: 'lab-nerd01',
    storageBucket: 'lab-nerd01.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClqQ-pj-k9KaC-GEeK1lKFDLFUwjUiCkg',
    appId: '1:1078406388474:ios:d292909fa877787761c743',
    messagingSenderId: '1078406388474',
    projectId: 'lab-nerd01',
    storageBucket: 'lab-nerd01.firebasestorage.app',
    iosBundleId: 'com.example.labNerd',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAip_2efh4UlyOEgxZXHMh0iHGu8dpnqa0',
    appId: '1:1078406388474:web:b79654a9575d799461c743',
    messagingSenderId: '1078406388474',
    projectId: 'lab-nerd01',
    authDomain: 'lab-nerd01.firebaseapp.com',
    storageBucket: 'lab-nerd01.firebasestorage.app',
    measurementId: 'G-3CSEG23MDP',
  );
}
