// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions android = FirebaseOptions(
    apiKey: dotenv.get("FIREBASE_API_KEY_ANDROID"),
    appId: dotenv.get("FIREBASE_APP_ID_ANDROID"),
    messagingSenderId: '1078406388474',
    projectId: 'lab-nerd01',
    storageBucket: 'lab-nerd01.firebasestorage.app',
  );

  static FirebaseOptions ios = FirebaseOptions(
    apiKey: dotenv.get("FIREBASE_API_KEY_IOS"),
    appId: dotenv.get("FIREBASE_APP_ID_IOS"),
    messagingSenderId: '1078406388474',
    projectId: 'lab-nerd01',
    storageBucket: 'lab-nerd01.firebasestorage.app',
    iosBundleId: 'com.example.labNerd',
  );

  static FirebaseOptions windows = FirebaseOptions(
    apiKey: dotenv.get("FIREBASE_API_KEY_WINDOWS"),
    appId: dotenv.get("FIREBASE_APP_ID_WINDOWS"),
    messagingSenderId: '1078406388474',
    projectId: 'lab-nerd01',
    authDomain: 'lab-nerd01.firebaseapp.com',
    storageBucket: 'lab-nerd01.firebasestorage.app',
    measurementId: 'G-3CSEG23MDP',
  );
}
